//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCOMProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayDetail
    {
        public int Id { get; set; }
        public string EId { get; set; }
        public int HId { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int State { get; set; }
        public string Remark { get; set; }
        public string Prove { get; set; }
        public int UsedDays { get; set; }
        public int BelongYear { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public string Reason { get; set; }
        public string AllowManager { get; set; }
        public string RangeDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Holiday Holiday { get; set; }
    }
}
