//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCOMProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayDetail
    {
        public int Id { get; set; }
        public string EId { get; set; }
        public int HId { get; set; }
        public Nullable<double> UsedHours { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool Allow { get; set; }
        public string Remark { get; set; }
        public double UsedDays { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Holiday Holiday { get; set; }
    }
}
