//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCOMProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftWork
    {
        public int Id { get; set; }
        public System.DateTime WorkDate { get; set; }
        public string Shift { get; set; }
        public bool WeekWork { get; set; }
    }
}
